name: Build EXE

on:
  push:
    branches: [main]
  workflow_dispatch:

# 添加权限配置
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install wcferry pillow python-dateutil cffi

      - name: Build EXE
        shell: cmd
        run: |
          echo "Build directory contents:"
          dir
          pyinstaller --onefile --hidden-import=cffi --hidden-import=_cffi_backend --add-data "C:\hostedtoolcache\windows\Python\3.10.11\x64\Lib\site-packages\wcferry;wcferry" wx_photo_archiver.py
          dir dist

      - name: Check Build Output
        shell: cmd
        run: |
          echo "Checking dist directory:"
          dir dist
          echo "Current directory:"
          dir

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: WxPhotoArchiver
          path: dist/WxPhotoArchiver.exe
