name: Build EXE

on:
  push:
    branches: [main]
  workflow_dispatch:

# 添加权限配置
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install wcferry pillow python-dateutil cffi

      - name: Build EXE
        shell: cmd
        run: |
          echo "Build directory contents:"
          dir
          echo "WCFerry path:"
          python -c "import wcferry,os;print(os.path.dirname(wcferry.__file__))"
          pyinstaller --onefile --hidden-import=cffi --hidden-import=_cffi_backend --add-data "C:\hostedtoolcache\windows\Python\3.10.11\x64\Lib\site-packages\wcferry;wcferry" wx_photo_archiver.py
          echo "After build:"
          dir
          echo "Dist folder contents:"
          dir dist

      - name: List All Files
        shell: cmd
        run: |
          echo "Full directory listing:"
          dir /s /b

      - name: Upload Artifact (with search)
        shell: cmd
        run: |
          for /r %%i in (WxPhotoArchiver.exe) do (
            echo Found: %%i
            echo "ARTIFACT_PATH=%%i" >> %GITHUB_ENV%
          )

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: WxPhotoArchiver
          path: ${{ env.ARTIFACT_PATH }}
